kind: Deployment
apiVersion: apps/v1
metadata:
  name: bikeshop-web
spec:
  selector:
    matchLabels:
      run: bikeshop-web
      name: bikeshop-web
  replicas: 1
  template:
    metadata:
      labels:
        run: bikeshop-web
    spec:
      containers:
        - name: bikeshop-web
          image: stylehopper/bikeshop.web:latest
